---
tags: ["cours", "pc", "terminale", "lycée", "enseignement scientifique"]
---

::: programme

+----------------------------------------------------+-----------------------------------------+
|                    **Savoirs**                     |            **Savoir-faire**             |
+====================================================+=========================================+
| - Pour que soit mise en œuvre une adaptation       | Analyser d’un point de vue global les   |
| efficace aux changements inéluctables et qu’en     | impacts de choix énergétiques majeurs : |
| soit atténué l’impact négatif, les choix           | exemple du nucléaire.                   |
| énergétiques supposent une compréhension globale   |                                         |
| du système Terre.                                  | Dans une étude de cas, analyser des     |
| - Ces choix doivent tenir compte de nombreux       | choix énergétiques locaux selon les     |
| critères et paramètres : disponibilité des         | critères et les paramètres mentionnés.  |
| ressources et adéquation aux besoins, impacts      |                                         |
| (climatique, écologique, sanitaire, agricole),     |                                         |
| vulnérabilités et gestion des risques,             |                                         |
| faisabilité, conséquences économiques et           |                                         |
| sociales. L’analyse de ces éléments de décision    |                                         |
| conduit le plus souvent à une recherche de         |                                         |
| diversification ou d’évolution des ressources      |                                         |
| (mix énergétique).                                 |                                         |
| - Les durées longues, liées à l’inertie de         |                                         |
| certains systèmes (infrastructures énergétiques,   |                                         |
| transports, production industrielle), sont à       |                                         |
| confronter à l’urgence de l’action.                |                                         |
| - La transition écologique des sociétés repose sur |                                         |
| la créativité scientifique et technologique,       |                                         |
| comme sur l’invention de nouveaux comportements    |                                         |
| individuels et collectifs (consommations,          |                                         |
| déplacements, relations Nord-Sud).                 |                                         |
+----------------------------------------------------+-----------------------------------------+  

:::

`youtube: DyVfHYkiv88`

::: appli

Préparer un oral sur une question personnelle relative au thème du chapitre : «Choix énergétiques
et impacts sur les sociétés.»

:::