---
tags: ["cours", "svt", "terminale", "lycée", "enseignement scientifique"]
---

::: programme

+----------------------------------------------------+------------------------------------------+
|                    **Savoirs**                     |             **Savoir-faire**             |
+====================================================+==========================================+
| Les structures anatomiques présentent des          | Expliquer l’origine d’une structure      |
| particularités surprenantes d’un point de vue      | anatomique en mobilisant les concepts de |
| fonctionnel, pouvant paraître sans fonction avérée | hasard, de variation, de sélection       |
| ou bien d’une étonnante complexité. Elles          | naturelle et d’adaptation (exemple de    |
| témoignent de l’évolution des espèces, dont la     | l’œil).                                  |
| nôtre. Les caractères anatomiques peuvent être le  |                                          |
| résultat de la sélection naturelle mais certains   | Interpréter des caractéristiques         |
| sont mieux expliqués par l’héritage de l’histoire  | anatomiques humaines en relation avec    |
| évolutive que par leur fonction.                   | des contraintes historiques (comme le    |
|                                                    | trajet de la crosse aortique), des       |
| L’évolution permet de comprendre des phénomènes    | contraintes de construction (comme le    |
| biologiques ayant une importance médicale.         | téton masculin), des compromis sélectifs |
| L’évolution rapide des organismes microbiens       | (comme les difficultés obstétriques) ou  |
| nécessite d’adapter les stratégies                 | des régressions en cours (comme les      |
| prophylactiques, les vaccins et les antibiotiques. | dents de sagesse).                       |
|                                                    |                                          |
| Depuis la révolution agricole, la pratique         | Mobiliser des concepts évolutionnistes   |
| intensive de la monoculture, la domestication et   | pour expliquer comment des populations   |
| l’utilisation de produits phytosanitaires ont un   | microbiennes pourront à longue échéance  |
| impact sur la biodiversité et son évolution.       | ne plus être sensibles à un vaccin (ou   |
|                                                    | un antibiotique) ou comment              |
|                                                    | l’utilisation de produits                |
|                                                    | phytosanitaires favorise le              |
|                                                    | développement de ravageurs des cultures  |
|                                                    | qui y sont résistants.                   |
+----------------------------------------------------+------------------------------------------+

:::
