---
tags: ["cours", "svt", "terminale", "lycée", "enseignement scientifique"]
---

::: programme

+----------------------------------------------------+------------------------------------------+
|                    **Savoirs**                     |             **Savoir-faire**             |
+====================================================+==========================================+
| L’espèce humaine actuelle (Homo sapiens) fait      | Analyser des matrices de comparaison de  |
| partie du groupe des primates et est plus          | caractères morpho-anatomiques résultant  |
| particulièrement apparentée aux grands singes avec | d’innovations évolutives afin d’établir  |
| lesquels elle partage des caractères               | des liens de parenté et de construire un |
| morpho-anatomiques et des similitudes génétiques.  | arbre phylogénétique.                    |
|                                                    |                                          |
| C’est avec le chimpanzé qu’elle partage le plus    | Mettre en relation la ressemblance       |
| récent ancêtre commun.                             | génétique entre les espèces de primates  |
|                                                    | et leur degré de parenté.                |
+----------------------------------------------------+------------------------------------------+
| Des arguments scientifiques issus de l’analyse     | Positionner quelques espèces fossiles    |
| comparée de fossiles permettent de reconstituer    | dans un arbre phylogénétique, à partir   |
| l’histoire de nos origines.                        | de l'étude de caractères.                |
|                                                    |                                          |
| L’étude de fossiles datés de 3 à 7 millions        |                                          |
| d’années montre des innovations caractéristiques   |                                          |
| de la lignée humaine (bipédie prolongée, forme de  |                                          |
| la mandibule).                                     |                                          |
+----------------------------------------------------+------------------------------------------+
| Le genre Homo regroupe l’espèce humaine actuelle   | Analyser des arguments scientifiques qui |
| et des espèces fossiles qui se caractérisent       | ont permis de préciser la parenté de     |
| notamment par le développement de la capacité      | Homo sapiens avec les autres Homo, et    |
| crânienne. Plusieurs espèces humaines ont cohabité | notamment la parenté éventuelle avec les |
| sur Terre.                                         | Néandertaliens ou les Dénisoviens.       |
|                                                    |                                          |
| Certains caractères sont transmis de manière non   |                                          |
| génétique : microbiote, comportements appris dont  |                                          |
| la langue, les habitudes alimentaires,             |                                          |
| l’utilisation d’outils...                          |                                          |
+----------------------------------------------------+------------------------------------------+

:::
