---
tags: ["cours", "svt", "terminale", "lycée", "enseignement scientifique"]
---

::: programme

+------------------------------------------------------+--------------------------------+
|                     **Savoirs**                      |        **Savoir-faire**        |
+======================================================+================================+
| Il y a environ 4,6 milliards d'années,               | Analyser des données, en lien  |
| l’atmosphère primitive était composée de N2, CO2 et  | avec l’évolution de la         |
| H2O. Sa composition actuelle est d’environ 78% de    | composition de l’atmosphère au |
| N2 et 21% de O2, avec des traces d’autres gaz (dont  | cours des temps géologiques.   |
| H2O, CO2, CH4, N2O).                                 |                                |
+------------------------------------------------------+--------------------------------+
| Le refroidissement de la surface de la Terre         | Déterminer l’état physique     |
| primitive a conduit à la liquéfaction de la          | de l’eau pour une température  |
| vapeur d’eau présente dans l’atmosphère initiale.    | et une pression donnée à       |
| L’hydrosphère s’est formée, dans laquelle s’est      | partir de son diagramme        |
| développée la vie.                                   | d’état.                        |
+------------------------------------------------------+--------------------------------+
| Les premières traces de vie sont datées d’il y a     | Mettre en relation la          |
| au moins 3,5 milliards d’années. Par leur            | production de O2 dans          |
| métabolisme photosynthétique, des cyanobactéries     | l’atmosphère avec des indices  |
| ont produit le dioxygène qui a oxydé, dans           | géologiques (oxydes de fer     |
| l’océan, des espèces chimiques réduites. Le          | rubanés, stromatolithes...).   |
| dioxygène s’est accumulé à partir de 2,4             |                                |
| milliards d’années dans l’atmosphère. Sa             |                                |
| concentration atmosphérique actuelle a été           |                                |
| atteinte il y a 500 millions d’années environ.       |                                |
+------------------------------------------------------+--------------------------------+
| Les sources et puits de dioxygène atmosphérique      | Ajuster les équations des      |
| sont aujourd’hui essentiellement liés aux êtres      | réactions chimiques            |
| vivants (photosynthèse et respiration) et aux        | d’oxydation du fer par le      |
| combustions.                                         | dioxygène.                     |
+------------------------------------------------------+--------------------------------+
| Sous l’effet du rayonnement ultraviolet solaire,     | Interpréter des spectres       |
| le dioxygène stratosphérique peut se dissocier,      | d’absorption de l’ozone et de  |
| initiant une transformation chimique qui aboutit à   | l’ADN dans le domaine          |
| la formation d’ozone. Celui-ci constitue une         | ultraviolet.                   |
| couche permanente de concentration maximale située à |                                |
| une altitude d’environ 30 km. La couche d’ozone      |                                |
| absorbe une partie du rayonnement ultraviolet        |                                |
| solaire et protège les êtres vivants de ses effets   |                                |
| mutagènes.                                           |                                |
+------------------------------------------------------+--------------------------------+
| Le carbone est stocké dans plusieurs réservoirs      | Analyser un schéma             |
| superficiels:l’atmosphère, les sols, les océans,     | représentant le cycle          |
| la biosphère et les roches. Les échanges de          | biogéochimique du carbone pour |
| carbone entre ces réservoirs sont quantifiés par     | comparer les stocks des        |
| des flux (tonne/an). Les quantités de carbone dans   | différents réservoirs et       |
| les différents réservoirs sont constantes lorsque    | identifier les flux principaux |
| les flux sont équilibrés. L’ensemble de ces          | de carbone d’origine           |
| échanges constitue le cycle du carbone sur Terre.    | anthropique ou non.            |
+------------------------------------------------------+--------------------------------+
| Les combustibles fossiles se sont formés à partir    |                                |
| du carbone des êtres vivants, il y a plusieurs       |                                |
| dizaines à plusieurs centaines de millions           |                                |
| d’années. Ils ne se renouvellent pas suffisamment    |                                |
| vite pour que les stocks se reconstituent:ces        |                                |
| ressources en énergie sont dites non                 |                                |
| renouvelables.                                       |                                |
+------------------------------------------------------+--------------------------------+

:::
