## Quiz

Si ce n'est pas déjà fait, **connectez-vous** sur le site d'OpenClassroom pour réaliser le quiz sur
le `javascript` disponible à l'adresse suivante:
<https://openclassrooms.com/courses/apprenez-a-coder-avec-javascript/exercises/489>

## Mini-projet : Créez un mini-jeu de devinette

[Consignes](http://exercices.openclassrooms.com/assessment/357?courseIdentifier=apprenez-a-coder-avec-javascript)

> Je vous propose de mobiliser vos nouvelles connaissances pour réaliser un mini-jeu de devinette.
> L’objectif de cette activité est d’écrire un programme `javascript` qui fait deviner un nombre
> entre 1 et 100.</br>
> Pour simplifier les choses, le programme initial qui vous est fourni permet de générer
> aléatoirement un nombre entre 1 et 100. Vous devez compléter ce programme pour que le joueur
> devine ce nombre en faisant des propositions successives. On considère que la saisie du joueur
> est toujours un nombre valide. À chaque tentative du joueur, le programme lui dit si le nombre
> qu’il a saisi est trop petit ou trop grand, jusqu’à ce que la solution soit devinée.</br>
> Pour obtenir le maximum de points possibles, limitez le nombre de tentatives du joueur. Au-delà
> de 6 essais infructueux, la partie est perdue !</br>
> Testez bien votre programme dans tous les cas possibles. Pensez au nommage des variables et à
> l’indentation de votre programme : ils font partie des critères d’évaluation.

[OpenClassroom licence CC-BY-SA](https://openclassrooms.com/fr/courses/6175841-apprenez-a-programmer-avec-javascript?archived-source=2984401){.cite-source}
