## Construire des tables de vérité

1. Produisez les tables de vérité pour les opérations suivantes:

   - **NAND** : $P \text{ NAND } Q = !(P \& Q)$
   - **NOR** : $P \text{ NOR } Q = !(P | Q)$
   - **XOR** : $P \text{ XOR } Q = (P \& !Q) | (!P \& Q)$

   ::: correction

   - **NAND** : $P \text{ NAND } Q = !(P \& Q)$

     +---+---+-----+--------+
     | P | Q | P&Q | !(P&Q) |
     +===+===+=====+========+
     | 0 | 0 | 0   | 1      |
     +---+---+-----+--------+
     | 0 | 1 | 0   | 1      |
     +---+---+-----+--------+
     | 1 | 0 | 0   | 1      |
     +---+---+-----+--------+
     | 1 | 1 | 1   | 0      |
     +---+---+-----+--------+

   - **NOR** : $P \text{ NOR } Q = !(P | Q)$

     +---+---+------+---------+
     | P | Q | P |Q | !(P |Q) |
     +===+===+======+=========+
     | 0 | 0 | 0    | 1       |
     +---+---+------+---------+
     | 0 | 1 | 1    | 0       |
     +---+---+------+---------+
     | 1 | 0 | 1    | 0       |
     +---+---+------+---------+
     | 1 | 1 | 1    | 0       |
     +---+---+------+---------+

   - **XOR** : $P \text{ XOR } Q = (P \& !Q) | (!P \& Q)$

     +---+---+-------+------+----------------+
     | P | Q | P& !Q | !P&Q | (P& !Q)|(!P&Q) |
     +===+===+=======+======+================+
     | 0 | 0 | 0     | 0    | 0              |
     +---+---+-------+------+----------------+
     | 0 | 1 | 0     | 1    | 1              |
     +---+---+-------+------+----------------+
     | 1 | 0 | 1     | 0    | 1              |
     +---+---+-------+------+----------------+
     | 1 | 1 | 0     | 0    | 0              |
     +---+---+-------+------+----------------+

   :::
   

2. Produire des tables de vérité pour :

   - $P \& !Q$

     ::: correction

     +---+---+----+------+
     | P | Q | !Q | P&!Q |
     +===+===+====+======+
     | 0 | 0 | 1  | 0    |
     +---+---+----+------+
     | 0 | 1 | 0  | 0    |
     +---+---+----+------+
     | 1 | 0 | 1  | 1    |
     +---+---+----+------+
     | 1 | 1 | 0  | 0    |
     +---+---+----+------+

     :::

   - $!P \&  !Q$

     ::: correction

     +-----+-----+------------+
     | P   | Q   | $!P \& !Q$ |
     +=====+=====+============+
     | 0   | 0   | 1          |
     +-----+-----+------------+
     | 0   | 1   | 0          |
     +-----+-----+------------+
     | 1   | 0   | 0          |
     +-----+-----+------------+
     | 1   | 1   | 0          |
     +-----+-----+------------+

     :::

   - $!P | !Q$

     ::: correction

     +-----+-----+------------+
     | P   | Q   | $!P  | !Q$ |
     +=====+=====+============+
     | 0   | 0   | 1          |
     +-----+-----+------------+
     | 0   | 1   | 1          |
     +-----+-----+------------+
     | 1   | 0   | 1          |
     +-----+-----+------------+
     | 1   | 1   | 0          |
     +-----+-----+------------+

     :::

   - $P \& Q \& R$

     ::: correction

     +---+---+---+-------------+
     | P | Q | R | $P\& Q\& R$ |
     +===+===+===+=============+
     | 0 | 0 | 0 | 0           |
     +---+---+---+-------------+
     | 0 | 0 | 1 | 0           |
     +---+---+---+-------------+
     | 0 | 1 | 0 | 0           |
     +---+---+---+-------------+
     | 0 | 1 | 1 | 0           |
     +---+---+---+-------------+
     | 1 | 0 | 0 | 0           |
     +---+---+---+-------------+
     | 1 | 0 | 1 | 0           |
     +---+---+---+-------------+
     | 1 | 1 | 0 | 0           |
     +---+---+---+-------------+
     | 1 | 1 | 1 | 1           |
     +---+---+---+-------------+

     :::

   - $!P \&  !Q \&  !R$

     ::: correction

     +-----+-----+-----+--------------------+
     | P   | Q   | R   | $!P \&  !Q \&  !R$ |
     +=====+=====+=====+====================+
     | 0   | 0   | 0   | 1                  |
     +-----+-----+-----+--------------------+
     | 0   | 0   | 1   | 0                  |
     +-----+-----+-----+--------------------+
     | 0   | 1   | 0   | 0                  |
     +-----+-----+-----+--------------------+
     | 0   | 1   | 1   | 0                  |
     +-----+-----+-----+--------------------+
     | 1   | 0   | 0   | 0                  |
     +-----+-----+-----+--------------------+
     | 1   | 0   | 1   | 0                  |
     +-----+-----+-----+--------------------+
     | 1   | 1   | 0   | 0                  |
     +-----+-----+-----+--------------------+
     | 1   | 1   | 1   | 0                  |
     +-----+-----+-----+--------------------+

     :::

   - $P \& Q \& R | P \&  !Q \& R$

     ::: correction

     +---+---+---+-------+---------+-----------------------------------+
     | P | Q | R | P&Q&R | P &!Q&R | $P \& Q \& R  | P \&  !Q \& R$    |
     +===+===+===+=======+=========+===================================+
     | 0 | 0 | 0 |       |         | 0                                 |
     +---+---+---+-------+---------+-----------------------------------+
     | 0 | 0 | 1 |       |         | 0                                 |
     +---+---+---+-------+---------+-----------------------------------+
     | 0 | 1 | 0 |       |         | 0                                 |
     +---+---+---+-------+---------+-----------------------------------+
     | 0 | 1 | 1 |       |         | 0                                 |
     +---+---+---+-------+---------+-----------------------------------+
     | 1 | 0 | 0 |       |         | 0                                 |
     +---+---+---+-------+---------+-----------------------------------+
     | 1 | 0 | 1 |       | 1       | 1                                 |
     +---+---+---+-------+---------+-----------------------------------+
     | 1 | 1 | 0 |       |         | 0                                 |
     +---+---+---+-------+---------+-----------------------------------+
     | 1 | 1 | 1 | 1     |         | 1                                 |
     +---+---+---+-------+---------+-----------------------------------+

     :::

## Expressions équivalentes

**Savoir-faire:** Utiliser une table de vérité pour montrer que deux expressions logiques sont
équivalentes

- Montrer que:

  $$
  P | ( !P \& Q)=P | Q
  $$

  ::: correction 

  +---+---+-------+-------------+---+------+
  | P | Q | !P &Q | P | (!P |Q) |   | P |Q |
  +===+===+=======+=============+===+======+
  | 0 | 0 |       | 0           |   | 0    |
  +---+---+-------+-------------+---+------+
  | 0 | 1 | 1     | 1           |   | 1    |
  +---+---+-------+-------------+---+------+
  | 1 | 0 |       | 1           |   | 1    |
  +---+---+-------+-------------+---+------+
  | 1 | 1 |       | 1           |   | 1    |
  +---+---+-------+-------------+---+------+

  :::

- Utiliser une table de vérité pour démontrer la propriété d’absorption de l’algèbre de Boole:

  $$
  P | P \& Q = P
  $$

  ::: correction 

  +---+---+-----+------------+
  | P | Q | P&Q | P | (P&Q)  |
  +===+===+=====+============+
  | 0 | 0 |     | 0          |
  +---+---+-----+------------+
  | 0 | 1 |     | 0          |
  +---+---+-----+------------+
  | 1 | 0 |     | 1          |
  +---+---+-----+------------+
  | 1 | 1 | 1   | 1          |
  +---+---+-----+------------+

  :::

- Montrer que:

  $$
  P | Q \& R = (P | Q) \& (P | R)
  $$

  ::: correction 

  +---+---+---+---------+-------+-------+------------------+
  | P | Q | R | P | Q&R | P | Q | P | R | (P | Q) &(P | R) |
  +===+===+===+=========+=======+=======+==================+
  | 0 | 0 | 0 |         |       |       |                  |
  +---+---+---+---------+-------+-------+------------------+
  | 0 | 0 | 1 |         |       | 1     |                  |
  +---+---+---+---------+-------+-------+------------------+
  | 0 | 1 | 0 |         | 1     |       |                  |
  +---+---+---+---------+-------+-------+------------------+
  | 0 | 1 | 1 | 1       | 1     | 1     | 1                |
  +---+---+---+---------+-------+-------+------------------+
  | 1 | 0 | 0 | 1       | 1     | 1     | 1                |
  +---+---+---+---------+-------+-------+------------------+
  | 1 | 0 | 1 | 1       | 1     | 1     | 1                |
  +---+---+---+---------+-------+-------+------------------+
  | 1 | 1 | 0 | 1       | 1     | 1     | 1                |
  +---+---+---+---------+-------+-------+------------------+
  | 1 | 1 | 1 | 1       | 1     | 1     | 1                |
  +---+---+---+---------+-------+-------+------------------+
  
  :::

## Simplifications d'expressions booléennes

Utilisez les lois de l'algèbre de Boole _(ne les apprenez pas!)_ pour simplifier ces expressions.

::: callout-tip

Utiliser le $\times$ pour le «ET» et le $+$ pour le «OU» pour pouvoir utiliser les règles
habituelles de développement et de factorisant de l'algèbre non booléen.

:::

1. Simplifier l'expression:

   $$
   (P | Q)\&(P |  !Q)
   $$
   
   Vérifier votre résultat avec une table de vérité.

   ::: correction

   $$
   (P | Q)\&(P |  !Q) = P\times P + P\times !Q + P\times Q + Q\times !Q = P + P\times (!Q + Q) + 0 = P
   $$

   +---+---+-------+-------------+--------------------+
   | P | Q | P | Q |  $P | !Q$*  | (P | Q) & (P | !Q) |
   +===+===+=======+=============+====================+
   | 0 | 0 |       | 1           |                    |
   +---+---+-------+-------------+--------------------+
   | 0 | 1 | 1     |             |                    |
   +---+---+-------+-------------+--------------------+
   | 1 | 0 | 1     | 1           | 1                  |
   +---+---+-------+-------------+--------------------+
   | 1 | 1 | 1     | 1           | 1                  |
   +---+---+-------+-------------+--------------------+
   
   :::


2. Démontrer l'expression de `XOR` utilisée dans l'exercice 1: $P \text{ XOR } Q = (P \& !Q)|(!P \&Q)$: 
   
   Pour cela commencer par remarquer que:
 
   $$
   \begin{aligned}
      0\ \text{XOR}\ Q\ &=\ Q \\
      1\ \text{XOR}\ Q\ &=\  !Q
   \end{aligned}
   $$
   
   Vérifier votre résultat avec une table de vérité.


## Recherche d'expressions équivalentes _(Plus dur)_

Exprimer sous forme simplifiée les expressions suivantes:

- $(P \& Q \& R) | (P \& Q \& S)$

  ::: correction
  
  $(P \& Q \& R) | (P \& Q \& S) = P \& Q \& (R|S)$
  
  :::

- $(!P | Q) \& (P | Q | S) \&  !S$

  ::: correction
  
  $(!P | Q) \& (P | Q | S) \&  !S = Q & !S$
  
  :::

- $P \&  !Q \&  !R | P \&  !Q \& R | P \& Q \& R$

  ::: correction
  
  $P \&  !Q \&  !R | P \&  !Q \& R | P \& Q \& R = P & (R | !Q)$
  
  :::


Vous pouvez vérifier vos résultats en Python en utilisant la bibliothèque `sympy` qui propose la
fonction `simplify_logic`(Attention la syntaxe utilisée est: ET: `&`, OU: `| et NON: `~`).

```python
from sympy import symbols
from sympy.logic import simplify_logic

P, Q, R, S, T = symbols('P Q R S T')

simplify_logic((~P|Q)&(P|Q|S)&~S) # renvoie Q & !S
```

La fonction propose deux modes de simplifications:

- Produit(ET) de sommes(OU): `simplify_logic(expr, 'cnf')`
- Somme(OU) de produit(ET): `simplify_logic(expr, 'dnf')`

```python
expr = "P&!Q&!R|P&!Q&R|P&Q&R"
simplify_logic(expr, 'cnf')   # renvoie P & (R | !Q)
simplify_logic(expr, 'dnf')   # renvoie (P & R) | (P & !Q)
```