---
tags:
  - cours
  - seconde
  - lycée
  - snt
  - seconde générale et technologique
  - sciences numériques et technologie
title: "Partie 7: Informatique embarquée"
order: 7
cours: true
tabnav: true
categories:
  - 2SNT
---

::: programme

+--------------------------------------+------------------------------------------------------------+
| Contenus                             | Capacités attendues                                        |
+======================================+============================================================+
| Systèmes informatiques embarqués     | Identifier des algorithmes de contrôle des comportements   |
|                                      | physiques à travers les données des capteurs, l’IHM et les |
|                                      | actions des actionneurs dans des systèmes courants.        |
+--------------------------------------+------------------------------------------------------------+
| Interface homme-machine (IHM)        | Réaliser une IHM simple d’un objet connecté.               |
+--------------------------------------+------------------------------------------------------------+
| Commande d’un actionneur,            | Écrire des programmes simples d’acquisition de données ou  |
| acquisition des données d’un capteur | de commande d’un actionneur.                               |
+--------------------------------------+------------------------------------------------------------+

:::

::: intro

Après avoir transformé les chaînes de montage des automobiles et les avions dans les années
quatre-vingt-dix, l'informatique intervient maintenant dans des domaines toujours plus nombreux :
automobile, réseau ferroviaire et transports urbains, domotique, robotique, loisirs, etc.,
conduisant à un nouvel internet des objets.

:::

::: appli

[Évaluation diagnostique](https://lienmini.fr/3389-702) PP150-151.

:::

## Interface Homme-Machine

: Interface Homme-Machine (IHM)

Moyens (matériels ou logiciels) prévus pour la communication entre un être humain et une machine. 

::: examples

- clavier
- souris
- __________
- __________
- __________


:::

## Les objets connectés

Les objets informatisés avaient autrefois des **interfaces homme-machine (IHM)** dédiées, souvent
dépendantes d’une liaison filaire directe. Mais les technologies du _Web_ intégrées au téléphone
portable permettent maintenant d’y rassembler les interfaces des objets du quotidien, ce qui en
simplifie et uniformise l’usage. Les objets informatisés deviennent ainsi connectés.

On estime à 50 milliards le nombre d’objets connectés en 2020.

